Support bulkhead group
spring-cloud/spring-cloud-circuitbreaker pull request #103
Opened 2021-04-05 16:01 UTC by Ferioney

Related to [Spring Cloud OpenFeign Issue 514](https://github.com/spring-cloud/spring-cloud-openfeign/issues/514).
These changes required the latest version of Spring Cloud Commons.

2021-04-06 18:37 UTC, ryanjbaxter requested changes
Please open the PR against the 1.0.x branch

2021-04-08 09:31 UTC, Ferioney commented
PR to the 1.0.x branch [104](https://github.com/spring-cloud/spring-cloud-circuitbreaker/pull/104/files)

2021-04-08 13:52 UTC, ryanjbaxter requested changes

2021-04-08 13:52 UTC, ryanjbaxter commented on spring-cloud-circuitbreaker-resilience4j/src/main/java/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4JCircuitBreaker.java
> +	public Resilience4JCircuitBreaker(String id,
Can we have the old constructor call this one?

2021-04-08 13:52 UTC, ryanjbaxter commented on spring-cloud-circuitbreaker-resilience4j/src/main/java/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4JCircuitBreakerFactory.java
> +	public org.springframework.cloud.client.circuitbreaker.CircuitBreaker create(String id, String groupName) {
Could we find a way to reuse code between the two `create` methods?

2021-04-08 13:55 UTC, closed without merging