Fixed Readme incorrect link to Spring commons docs
spring-cloud/spring-cloud-circuitbreaker pull request #111
Opened 2021-05-12 06:31 UTC by RajatArora08

Found the link was incorrect. Fixed it.

2021-05-12 11:31 UTC, spencergibb requested changes
This is a generated file. Please change the one in docs/src/main/asciidoc

2021-05-12 13:53 UTC, ryanjbaxter requested changes
Changes need to be made in this file or else they will be overwritten 
https://github.com/spring-cloud/spring-cloud-circuitbreaker/blob/main/docs/src/main/asciidoc/README.adoc

2021-05-13 07:56 UTC, RajatArora08 commented
@spencergibb @ryanjbaxter thanks for pointing it out. Fixed it in the correct place.

2021-05-13 14:08 UTC, ryanjbaxter approved these changes

2021-05-13 14:08 UTC, merged