Add ability to use semaphore bulkhead by default
spring-cloud/spring-cloud-circuitbreaker pull request #136
Opened 2022-02-18 21:18 UTC by robertmcnees

2022-02-21 14:31 UTC, ryanjbaxter requested changes

2022-02-21 14:31 UTC, ryanjbaxter commented on spring-cloud-circuitbreaker-resilience4j/src/main/java/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4jBulkheadProvider.java
>  	public Resilience4jBulkheadProvider(ThreadPoolBulkheadRegistry threadPoolBulkheadRegistry,
Mark this as `@Deprecated`

2022-02-21 14:31 UTC, ryanjbaxter commented on spring-cloud-circuitbreaker-resilience4j/src/main/java/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4JConfigurationProperties.java
> +	boolean isEnableSemaphoreDefaultBulkhead() {
Make these `public`

2022-02-21 14:31 UTC, ryanjbaxter commented on spring-cloud-circuitbreaker-resilience4j/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> +mock-maker-inline
What is this for?

2022-02-22 13:36 UTC, robertmcnees commented on spring-cloud-circuitbreaker-resilience4j/src/test/java/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4JDefaultSemaphoreBulkheadIntegrationTest.java
> +	@SpyBean
The new mockito-extensions file is used so that this SpyBean (and the 1 below it) can mock a final class

2022-02-22 13:45 UTC, ryanjbaxter approved these changes

2022-02-22 13:50 UTC, merged

2022-02-22 14:20 UTC, wind57 commented
this will go to `main` also, right? because I could use that mockito extension for final classes/methods too in a diff PR. thank you for the answer

2022-02-22 14:24 UTC, ryanjbaxter commented
Already there