Issue-61
spring-cloud/spring-cloud-circuitbreaker pull request #88
Opened 2021-02-12 17:19 UTC by Ferioney

included resilience4J spring boot 2 module
Fixes gh-61

2021-02-16 18:52 UTC, ryanjbaxter requested changes
This includes changes from #87, please separate the two.

2021-02-17 16:08 UTC, ryanjbaxter requested changes

2021-02-17 16:08 UTC, ryanjbaxter commented on README.adoc
> +You can configure CircuitBreaker and TimeLimiter instances in Spring Boot’s `application.yml` config file. Property configuration has higher priority that Java `Customizer` configuration.
"in Spring Boot’s  `application.yml`" -> "in your application's configuration properties"

2021-02-17 17:05 UTC, Ferioney commented on spring-cloud-circuitbreaker-resilience4j/src/main/java/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4JAutoConfiguration.java
> -	@Configuration(proxyBeanMethods = false)
Reverted. 
Anyway, CircuitBreaker and TimeLimiter are automatically published on the Metrics, [Resilience4j Spring Boot 2](https://resilience4j.readme.io/docs/getting-started-3#metrics-endpoint)

2021-02-17 18:50 UTC, ryanjbaxter requested changes

2021-02-17 18:50 UTC, ryanjbaxter commented on README.adoc
> +You can configure CircuitBreaker and TimeLimiter instances in your application's configuration properties config file. Property configuration has higher priority than Java `Customizer` configuration.
remove "config"

2021-02-17 18:50 UTC, ryanjbaxter commented on spring-cloud-circuitbreaker-resilience4j/src/main/java/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4JAutoConfiguration.java
> -	@Configuration(proxyBeanMethods = false)
The `@Configuration` line still need to be added back

2021-02-17 18:50 UTC, ryanjbaxter commented on spring-cloud-circuitbreaker-resilience4j/src/main/java/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4JCircuitBreaker.java
> +		TimeLimiter timeLimiter = timeLimiterRegistry != null ? timeLimiterRegistry.timeLimiter(id, timeLimiterConfig)
Seems to make sense to move this to the old constructor

2021-02-17 18:50 UTC, ryanjbaxter commented on spring-cloud-circuitbreaker-resilience4j/src/main/java/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4JCircuitBreakerFactory.java
> -		this.circuitBreakerRegistry = registry;
Add this line back

2021-02-18 15:19 UTC, ryanjbaxter approved these changes

2021-02-18 15:20 UTC, merged